version: '3.5'

services:

  postgres:
    image: postgres
    container_name: dd_postgres
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres

  desafio:
    image: azimuty/desafio:nodejs
    container_name: desafio_desenvolvedor
    restart: on-failure
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_ADDRESS: 172.17.0.1
      POSTGRES_PORT: 5432